### PR TITLE
✨ support cusdis comment plugin

### PR DESCRIPTION
**Pull request by TennyZhuang**
close #474

### CODE REVIEW

**Comment by Edwardzcn** [comment]
Close #479

**Comment by djyde** [comment]
I tried to remove this line https://github.com/fluid-dev/hexo-theme-fluid/blob/master/source/js/utils.js#L177 and the error disappeared. 

I don't know what's this function call did.

**Comment by zkqiang** [comment]
Thanks
This error may be my problem and I will fix it

**Comment by zkqiang** [comment]
@djyde 
The reason for this error, I think that this `function $` overwrite `jQuery $`

image

image

**Comment by djyde** [comment]
> @djyde
> The reason for this error, I think that this `function $` of `cusdis.es.js` overwrite `jQuery $`, so can you fix it?
> 
> image
> 
> image

This function is generated by Svelte, I need to find out if there are the same issues in another Svelte projects which is used in jQuery environment.

**Comment by djyde** [comment]
> @djyde
> The reason for this error, I think that this `function $` of `cusdis.es.js` overwrite `jQuery $`, so can you fix it?
> 
> image
> 
> image

This function is generated by Svelte, I need to find out if there are the same issues in another Svelte projects which is used in jQuery environment.

**Comment by TennyZhuang** [comment]
try to call `jQuery.noConflict()` in some entry scripts may be helpful.

**Comment by zkqiang** [comment]
@TennyZhuang @djyde 
Thanks, I used `jQuery` instead of `$`, there is no error now

**Pull request merged**
